# Generated by Django 4.2.1 on 2023-07-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientsIpAddresses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=100, verbose_name="Адрес Ip")),
            ],
            options={
                "verbose_name": "Адрес Ip",
                "verbose_name_plural": "Адреса Ip",
            },
        ),
        migrations.CreateModel(
            name="Coordinates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude_coordinate",
                    models.FloatField(verbose_name="Широта (координата)"),
                ),
                (
                    "longitude_coordinate",
                    models.FloatField(verbose_name="Долгота (координата)"),
                ),
            ],
            options={
                "verbose_name": "Координата",
                "verbose_name_plural": "Координаты",
                "ordering": ["id"],
            },
        ),
    ]
