# Generated by Django 4.2.1 on 2023-07-31 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("map_app", "0001_initial"),
        ("trash_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coordinates",
            name="coordinates",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizations_coordinates",
                to="trash_app.organizations",
                verbose_name="Координаты организации",
            ),
        ),
    ]
