# Generated by Django 4.2.1 on 2023-07-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientsipaddresses",
            options={"verbose_name": "Ip-адрес", "verbose_name_plural": "Ip-адреса"},
        ),
        migrations.AlterField(
            model_name="clientsipaddresses",
            name="ip",
            field=models.CharField(max_length=100, verbose_name="Ip-адрес"),
        ),
    ]
