# Generated by Django 4.2.1 on 2023-08-02 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_subscribedusers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="subscribedusers",
            options={
                "verbose_name": "Пользователь, который подписан на рассылку",
                "verbose_name_plural": "Пользователи, которые подписаны на рассылку",
            },
        ),
        migrations.AlterField(
            model_name="subscribedusers",
            name="created_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Время создания подписки",
            ),
        ),
    ]
