# Generated by Django 4.2.1 on 2023-07-31 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Содержание ответа")),
                (
                    "time_added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время ответа"
                    ),
                ),
                (
                    "time_changed",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время отредактированного ответа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на заданный вопрос",
                "verbose_name_plural": "Ответы на заданные вопросы",
                "ordering": ["time_added"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
                (
                    "photo_for_article",
                    models.ImageField(
                        upload_to="images/%Y/%m/%d/", verbose_name="Фото для статей"
                    ),
                ),
                ("description", models.TextField(verbose_name="Текст статьи")),
                (
                    "release_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Публикация"),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["release_date"],
            },
        ),
        migrations.CreateModel(
            name="Organizations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        max_length=100, verbose_name="Название организации"
                    ),
                ),
                (
                    "organization_description",
                    models.TextField(verbose_name="Описание деятельности организации"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
                (
                    "address",
                    models.CharField(max_length=150, verbose_name="Адрес организации"),
                ),
                (
                    "telephone_number",
                    models.CharField(
                        max_length=16,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Телефонный номер должен быть введён в формате: '+999999999'. Допускается до 15 цифр.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "web_address",
                    models.URLField(blank=True, verbose_name="Адрес сайта"),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        verbose_name="Статус организации (активна или нет)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_for_material",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="Цена за 1 кг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цены за материал",
                "verbose_name_plural": "Цены за материалы",
                "ordering": ["organizations_different_prices"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text="Не более 50 символов",
                        max_length=50,
                        verbose_name="Заголовок",
                    ),
                ),
                ("content", models.TextField(verbose_name="Содержание вопроса")),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
            ],
            options={
                "verbose_name": "Задать вопрос",
                "verbose_name_plural": "Задать вопросы",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="TrashMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название материала"),
                ),
                (
                    "image_of_material",
                    models.ImageField(
                        upload_to="images/%Y/%m/%d/",
                        verbose_name="Изображения материала",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал",
                "verbose_name_plural": "Материалы",
                "ordering": ["name"],
            },
        ),
    ]
