# Generated by Django 4.2.1 on 2023-07-31 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trash_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_questions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор вопроса",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="question_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="material_different_prices",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_prices",
                to="trash_app.trashmaterial",
                verbose_name="Цены на разные материалы",
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="organizations_different_prices",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_prices",
                to="trash_app.organizations",
                verbose_name="Цены у разных организаций",
            ),
        ),
        migrations.AddField(
            model_name="organizations",
            name="material",
            field=models.ManyToManyField(
                related_name="material_in_organization",
                to="trash_app.trashmaterial",
                verbose_name="Материалы",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="material_name",
            field=models.ManyToManyField(
                blank=True,
                related_name="article_of_material",
                to="trash_app.trashmaterial",
                verbose_name="Материалы",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="organization_name",
            field=models.ManyToManyField(
                blank=True,
                related_name="article_for_organization",
                to="trash_app.organizations",
                verbose_name="Организации",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="trash_app.question",
                verbose_name="Ответ",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_answers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор ответа",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="answer_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="answer_replies",
                to="trash_app.answer",
            ),
        ),
    ]
