# Generated by Django 4.2.1 on 2023-07-31 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trash_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizations",
            name="telephone_number",
            field=models.CharField(
                max_length=16,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Телефонный номер должен быть введён в формате: '+999999999'. Допускается до 15 цифр.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Телефонный номер",
            ),
        ),
    ]
