# Generated by Django 4.2.1 on 2023-07-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map_app", "0002_initial"),
        ("trash_app", "0003_alter_organizations_telephone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizations",
            name="views",
            field=models.ManyToManyField(
                blank=True,
                related_name="question_views",
                to="map_app.clientsipaddresses",
            ),
        ),
    ]
