# Generated by Django 4.2.1 on 2023-07-31 10:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("map_app", "0003_alter_clientsipaddresses_options_and_more"),
        ("trash_app", "0004_organizations_views"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "ordering": ["time_added"],
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="description",
            field=tinymce.models.HTMLField(verbose_name="Текст статьи"),
        ),
        migrations.AlterField(
            model_name="organizations",
            name="organization_description",
            field=tinymce.models.HTMLField(
                verbose_name="Описание деятельности организации"
            ),
        ),
        migrations.AlterField(
            model_name="organizations",
            name="views",
            field=models.ManyToManyField(
                blank=True,
                related_name="question_views",
                to="map_app.clientsipaddresses",
                verbose_name="Ip-адреса просмотревших",
            ),
        ),
    ]
