# Generated by Django 4.2.1 on 2023-08-02 06:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("trash_app", "0005_alter_answer_options_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="organizations",
            name="organization_description",
            field=tinymce.models.HTMLField(),
        ),
    ]
